# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e2cda2d20ad0f1066f02e4cba0897fa3edafab9bf931a8791155d49f14b20d78cb95925303fba966b2e4a6ce0179d6273fe77d4dca15207d352b42296b3244

test:
  secret_key_base: 102fce7b3f554f2ff521b67064bfe7ecf97095faa2250b5b7425f664e214572fa6a1a64880110509a72f722492570a4062d19aa181948d516d115c535dbfc26c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
